package com.weeeeestern.dtlogs.slack;


import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.weeeeestern.dtlogs.dataset.QuestionDataset;
import com.weeeeestern.dtlogs.git.GitHubClient;
import com.weeeeestern.dtlogs.history.HistoryService;
import com.weeeeestern.dtlogs.llm.GeminiClient;
import com.weeeeestern.dtlogs.md.MarkdownService;
import com.weeeeestern.dtlogs.search.TavilyClient;


@RestController
@RequestMapping("/slack")
public class SlackController {


    private final QuestionDataset dataset;
    private final HistoryService historyService;
    private final TavilyClient tavilyClient;
    private final SlackService slackService;
    private final MarkdownService markdownService;
    private final GeminiClient geminiClient;
    private final GitHubClient githubClient;
    private final String channelId;

    public SlackController(
            QuestionDataset dataset,
            HistoryService historyService,
            TavilyClient tavilyClient,
            SlackService slackService,
            MarkdownService markdownService,
            GeminiClient geminiClient,
            GitHubClient githubClient,
            @Value("${slack.channel-id:}") String channelId) {
        this.dataset = dataset;
        this.historyService = historyService;
        this.tavilyClient = tavilyClient;
        this.slackService = slackService;
        this.markdownService = markdownService;
        this.geminiClient = geminiClient;
        this.githubClient = githubClient;
        this.channelId = channelId;
    }

    @PostMapping("/category")
    public ResponseEntity<String> category(@RequestParam("user_id") String userId,
                                           @RequestParam("text") String category) {
        List<String> questions = dataset.getQuestions(category);
        String question = historyService.pickQuestion(userId, category, questions);
        if (question == null) {
            return ResponseEntity.ok("모든 질문을 소진했습니다. /reset " + category + " 로 초기화해주세요.");
        }
        String link = tavilyClient.search(question);
        slackService.postMessage(channelId,
                "📘 오늘의 질문: " + question + " 🔗 블로그 링크: " + link +
                        " 👉 /정리 명령어로 오늘의 학습 내용을 정리해주세요!");
        historyService.recordPresented(userId, category, question, link);
        return ResponseEntity.ok("질문을 전송했습니다.");
    }

    @PostMapping("/summary")
    public ResponseEntity<String> summary(@RequestBody SummaryRequest req) throws IOException {
        LocalDate today = LocalDate.now();
        String keywords = geminiClient.extractKeywords(req.question());
        String markdown = markdownService.render(today, req.category(), req.question(), keywords, req.link(),
                req.userConcept(), req.userOral(), req.userExpressions(), req.userReflection());
        var path = markdownService.save(markdown, today, req.category());
        String branch = "feat/tech-log-" + today.format(DateTimeFormatter.BASIC_ISO_DATE);
        githubClient.commitAndCreatePR(branch, path.toString(), markdown, "Tech Log for " + today, "Generated by bot");
        historyService.recordCompleted(req.userId(), req.category(), req.question());
        return ResponseEntity.ok("정리 완료");
    }

    @PostMapping("/reset")
    public ResponseEntity<String> reset(@RequestParam("user_id") String userId,
                                        @RequestParam("text") String category) {
        historyService.resetCategory(userId, category);
        return ResponseEntity.ok("초기화했습니다.");

    }
}
